# Generated by Django 5.2.12 on 2026-03-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_body', models.CharField(max_length=1000)),
                ('post_date', models.DateTimeField(verbose_name='date posted')),
            ],
        ),
    ]
