# Generated by Django 6.0.3 on 2026-03-17 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_course_code_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.department'),
        ),
    ]
