# Generated by Django 6.0.3 on 2026-05-02 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0003_prof_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='syllabi/')),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('I', 'Intercession')], max_length=1)),
                ('school_year', models.CharField(help_text='e.g. 2024-2025', max_length=9)),
                ('version', models.PositiveIntegerField(default=1)),
                ('verified', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.course')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.department')),
                ('prof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.prof')),
            ],
            options={
                'unique_together': {('prof', 'course', 'semester', 'school_year', 'version')},
            },
        ),
    ]
