# Generated by Django 6.0.3 on 2026-05-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name': 'Syllabus', 'verbose_name_plural': 'Syllabi'},
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='file',
            field=models.FileField(upload_to='syllabi/syllabi/'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='semester',
            field=models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('0', 'Intercession')], max_length=1),
        ),
    ]
